import logging
from datetime import datetime

import pytz


def create_message(parsnip_url, diamanten_data):
    ger = pytz.timezone('Europe/Berlin')
    nyse = pytz.timezone('America/New_York')

    vol = 0
    volume_desc = []
    for item in diamanten_data['sources']:
        vol += item['volume']
        volume_desc.append("[%d at %s](%s)" % (item['volume'], item['short_name'], item['link']))

    now = diamanten_data['now']
    rate = diamanten_data['euro2usd']
    price = diamanten_data['price']
    collated_volume = '\n+ '.join(volume_desc)

    message_parts = [
        "German market update ",
        "(local time: %s)" % now.astimezone(ger).strftime("%T"),
        "(nyse time: %s)" % now.astimezone(nyse).strftime("%T"),
        "(generated by %s)" % diamanten_data['created_by'],
        "  ",
        "**$%.2f** ([€%.2f](https://www.tradegate.de/orderbuch.php?isin=US36467W1099)@" % (price * rate, price),
        "[%.4f](https://www.onvista.de/devisen/Eurokurs-Euro-Dollar-EUR-USD)) " % rate,
        "  ",
        "**volume: %s** (" % vol,
        collated_volume,
        ")",
        "  ",
        "  "
    ]

    if parsnip_url is not None:
        message_parts.append("[Visit the Diamantenhände post as well](%s)" % parsnip_url)

    return '\n'.join(message_parts)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    testdata = {
        'now': datetime.now(),
        'euro2usd': 1.7,
        'price': 200.75,
        'sources': [
            {
                'name': 'TradeGate', 'short_name': 'TG',
                'link': 'https://www.tradegate.de/orderbuch.php?isin=US36467W1099',
                'volume': 200
            },
            {
                'name': 'Lang&Schwarz Exchange', 'short_name': 'LS-X',
                'link': 'https://www.ls-x.de/de/aktie/gamestop-aktie',
                'volume': 201
            },
            {
                'name': 'Lang&Schwarz Tradecenter', 'short_name': 'LS-TC',
                'link': 'https://www.ls-tc.de/de/aktie/gamestop-aktie',
                'volume': 202
            },
            {
                'name': 'gettex', 'short_name': 'gettex',
                'link': 'https://www.gettex.de/suche/?tx_indexedsearch[sword]=GS2C',
                'volume': 203
            }
        ],
        'created_by': "halfdane's [Diamantenbot](https://github.com/halfdane/diamantenbot)"
    }
    logging.info(create_message(None, testdata))
