from datetime import datetime
from pyquery import PyQuery as pq
import pytz
import logging
import re
import requests


def get_trade_gate_information():
    d = pq('https://www.tradegate.de/orderbuch.php?isin=US36467W1099')
    stueck__text = d('#stueck').text()
    stueck__text = re.sub('[^\d]', '', stueck__text)
    v = int(stueck__text)

    vol = \
        get_gettex_volume() + \
        get_ls_volume('https://www.ls-tc.de/de/aktie/gamestop-aktie') + \
        get_ls_volume('https://www.ls-x.de/de/aktie/gamestop-aktie') + \
        v

    return {
        'price': float(d('#last').text().replace(',', '.')),
        'volume': vol
    }


def get_ls_volume(url):
    d = pq(url)
    lines = d('tr [field="tradeTime"][decimals="2"]') \
        .filter(lambda i, this: re.match('[\d:]{8}.*?', pq(this).text())) \
        .parents('tr') \
        .find('[field="tradeSize"]').items()
    return sum([int(i.text()) for i in lines if i.text().isdigit()])


def get_gettex_volume():
    f = pq('https://www.gettex.de/suche/?tx_indexedsearch%5Bsword%5D=GS2C',
           headers={'user-agent': 'pyquery', 'cookie': 'cookie_optin=essential:1'})
    data_endpoint = f('#heading-timesSales').attr("data-ajax-uri")

    r = requests.get('https://www.gettex.de'+data_endpoint, headers={'user-agent': 'pyquery'})
    d = pq(r.json()["data"])
    return int(d('tbody tr:first td:last').text())


def eur_to_usd():
    d = pq('https://www.onvista.de/devisen/Eurokurs-Euro-Dollar-EUR-USD')
    return float(d('.KURSDATEN span[data-push]').eq(0).text().replace(',', '.'))


def create_message():
    ger = pytz.timezone('Europe/Berlin')
    nyse = pytz.timezone('America/New_York')

    now = datetime.now()
    tg = get_trade_gate_information()
    rate = eur_to_usd()

    return '\n'.join([
        "German market update (local time: %s) (nyse time: %s) "
        "(generated by halfdane's [Diamantenbot](https://github.com/halfdane/diamantenbot))  " %
        (now.astimezone(ger).strftime("%T"), now.astimezone(nyse).strftime("%T")),
        "**$%.2f** ([€%.2f](https://www.tradegate.de/orderbuch.php?isin=US36467W1099)@"
        "[%.4f](https://www.onvista.de/devisen/Eurokurs-Euro-Dollar-EUR-USD)) **volume: %s** ("
        "[TG](https://www.tradegate.de/orderbuch.php?isin=US36467W1099)+"
        "[LS-X](https://www.ls-x.de/de/aktie/gamestop-aktie)+"
        "[LS-TC](https://www.ls-tc.de/de/aktie/gamestop-aktie)+"
        "[GETTEX](https://www.gettex.de/suche/?tx_indexedsearch%%5Bsword%%5D=GS2C))  " % (
            tg['price'] * rate, tg['price'], rate, tg['volume'])
    ])


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    logging.info(create_message())
